### ISSUE TITLE
Problems with the code base.

### ISSUE THREAD

**Issue by AI-madman** [Mayankm96/Stereo-Odometry-SOFT#5]
You have a few problems with this code:

one your code makes it seem that the location of a feature point is the same in each stereo pair this leads to Matlab thinking that no translation exists and so print an error message to the console reading that the "." operation is not valid for an empty object.

Two you remake the entire graph at each time instance making it really slow.

Three there's no tracking of results.

four there's no way to turn bucketing on and off easily

**Comment by Mayankm96** [comment]
Thank you for the comments. Those would make some excellent extensions!

Unfortunately, I don't have the time right to actively maintain this repository. However, I always welcome pull requests to add more features to the code. :)
